### ISSUE TITLE
增加List<char>

### ISSUE THREAD

**Issue by yatesliang** [lamuguo/oj-issues#2]
后续用到的字母大小写转换，凯撒密码等需要输入/输出字符串

**Comment by lamuguo** [comment]
@yatesliang 这个我改好了，你可以把需要list<char>的case提上来，我来push一个新的版本测一下。

然后其它的你也可以慢慢提上来。

**Comment by lamuguo** [comment]
list<string> is supported.

**Comment by yatesliang** [comment]
题目1010, List<char>似乎没能正确跑，不知道是不是我的格式问题（admin用户的代码是solution）
